%% v3 data
h = fopen('bandit_v3.csv','w');
fprintf(h,'ID,block,trial,whichFilled,choice,responseTime,pointsWon,blockWinnings,fillColour\n')
for i = 1:numel(v3data)
    fprintf(h,'%.0f,%.0f,%.0f,%s,%s,%.0f,%.0f,%.0f,%s\n',...
        v3data(i).ID,...
        v3data(i).block,...
        v3data(i).trial,...
        v3data(i).whichFilled,...
        v3data(i).choice,...
        v3data(i).responseTime,...
        v3data(i).pointsWon,...
        v3data(i).blockWinnings,...
        v3data(i).fillColour);
end

%% v4 data
fclose(h)
h = fopen('test.csv','w');
fprintf(h,'ID,block,trial,whichFilled,choice,responseTime,pointsWon,blockWinnings,fillColour\n')
for i = 1:numel(v3data)
    fprintf(h,'%.0f,%.0f,%.0f,%s,%s,%.0f,%.0f,%.0f,%s\n',...
        v3data(i).ID,...
        v3data(i).block,...
        v3data(i).trial,...
        v3data(i).whichFilled,...
        v3data(i).choice,...
        v3data(i).responseTime,...
        v3data(i).pointsWon,...
        v3data(i).blockWinnings,...
        v3data(i).fillColour);
end

fclose(h)
h = fopen('bandit_v4.csv','w');
fprintf(h,'ID,block,trial,whichFilled,choice,responseTime,pointsWon,blockWinnings,tagText\n')
for i = 1:numel(v4data)
    fprintf(h,'%.0f,%.0f,%.0f,%s,%s,%.0f,%.0f,%.0f,%s\n',...
        v4data(i).ID,...
        v4data(i).block,...
        v4data(i).trial,...
        v4data(i).whichFilled,...
        v4data(i).choice,...
        v4data(i).responseTime,...
        v4data(i).pointsWon,...
        v4data(i).blockWinnings,...
        v4data(i).tagText);
end

fclose(h)